# ✅ Name of the Workflow
name: Pipeline CI/CD Backend-api

# ✅ Trigger this workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  run-unit-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: clone soure code
        uses:  actions/checkout@v5
        
      - name: install dependencies
        run: npm install

      - name: run unit test
        run: npm run test


     
  

# jobs:
#   -name: 